# Generated by Django 4.0.3 on 2022-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_contato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
