# Generated by Django 4.0.3 on 2022-05-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_contato_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='image',
            new_name='imagem',
        ),
    ]
